platform :ios, '12.1'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'MyDogwalk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyDogwalk
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Kingfisher'
	
end
